print('Exempplo')
lingua = "DJJEUE DKEKD IKWKKSI KSKKS KMSKW KSKWK".split()
novalista = map(lambda x: x.lower(), lingua)
print(f'A nova lista é {novalista}\n')
novalista = list(novalista)
print(f'Agora é assim {novalista}')
